name: hallucination_llm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - openpyxl
  - tqdm
  - pip
  - datasets
  - wordcloud
  - nltk
  - pip:
      - imbalanced-learn
      - missingno
      - torch
      - torchvision
      - torchaudio
      - transformers
